# Generated by Django 2.2.14 on 2022-11-18 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221118_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallets',
            name='date_created',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, max_length=250, null=True),
        ),
    ]
